
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: contact_list
  password: 123456

development:
  <<: *default
  database: contact_list_development

test:
  <<: *default
  database: contact_list_test

production:
  <<: *default
  database: contact_list_production
  username: contact_list
